version: "3.5"

services:
  web:
    build: ./
    container_name: agorize-apache
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/html:Z
      - ./logs:/var/log/httpd

  database:
    image: mysql:8.0
    volumes:
      - ./docker/mysqlconf:/etc/mysql/conf.d
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ProjetAgorize
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    ports:
      - "8080:80"
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: database

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"

  bootstrap:
    image: webdevops/bootstrap

